# Generated by Django 4.1.5 on 2023-01-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='weekId',
        ),
    ]
