# Generated by Django 4.1.5 on 2023-01-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_sales_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='producer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.producer'),
        ),
    ]
