# Generated by Django 4.1.5 on 2023-01-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_device_producer_device_producercompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='producerCompany',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
