# Generated by Django 4.1.5 on 2023-01-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_producer_device_producercompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='producerCompany',
            new_name='producer',
        ),
    ]
