# Generated by Django 4.1.5 on 2023-01-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_producercompany_device_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='producer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='app.producer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.device'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.week'),
        ),
        migrations.CreateModel(
            name='PredictedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted', to='app.device')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted', to='app.week')),
            ],
        ),
    ]
