# Generated by Django 4.1.5 on 2023-01-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isEOL',
            field=models.BooleanField(default=False),
        ),
    ]
